name: my second project

on: push

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "I've been triggred by a(n) ${{github.event_name}} event."